# Generated by Django 4.2.5 on 2023-10-21 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Group_Details',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('donated_blood_to', models.CharField(max_length=100)),
                ('received_blood_from', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bloodbank_System',
            fields=[
                ('district_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('email', models.EmailField(max_length=150, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='login_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBMS_APP.custom_user')),
            ],
        ),
        migrations.CreateModel(
            name='Bloodbank_Details',
            fields=[
                ('bloodbank_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bloodbank_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBMS_APP.bloodbank_system')),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Stuck_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBMS_APP.blood_group_details')),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBMS_APP.bloodbank_details')),
                ('quantity', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('doctorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('specialization', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donor_Details',
            fields=[
                ('donorid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('do_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('blood_group', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
